[tool.poetry]
name = "twitterclone-master"
version = "0.1.0"
description = ""
authors = ["Kathy <trankathy009@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^2.2.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
